//lets talk abt relation operator 

//HERE IT IS ACTUALLY THE COMPARISION BETWEEN TOW STRINGS WHEATHER IT IS GREATER OR LESSER OF EACH OTHER
let a = "Narayana"
let b = "Chavan"
let res = a>b
console.log(res)
// HERE FRO COMPAIRSION WE ACTUALLLY USED ASCII VALUES OF THOSE STRINGS .
//WHERE A = 64 ......... Z = 91

let Name = "90"
let y = 90
let w = Name == y
console.log(w)
// HERE IN COMPARISION OF 'STRING'  &  'NUMBER' IW WILL PRINT TRUE COZ IT WILL CONVERTING THE STRING INTO THE NUMBER (TYPE COERCION)
//BUT IT IS NOT GOING TO WORK AS WE ADDIN BUGS THOUGH

let val1 = "90"
let val2 = 90
let result = val1 === val2
console.log(result)
// HERE WE DID NOT CREATE ANY BUGS HERE WE USE "STRICTLY EQUALUTY OPERATOR"  IN JAVASCRIPT
 
